{
 "title": "Maze Gesture API Metrics",
 "tags": [
  "maze",
  "gesture",
  "api"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Duration (Seconds)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum",
     "legendFormat": "Total Duration"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "x": 0, "y": 9, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Request Duration Average",
   "type": "graph",
   "gridPos": { "x": 0, "y": 18, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "Avg Duration (1m)"
    }
   ]
  }
 ]
}